os: osx
osx_image: xcode10.1
language: swift
script: 
- if [ ($TRAVIS_BRANCH = 'master') OR ($TRAVIS_BRANCH =~ ^release.*)]; then touch prodFile2; echo "hello" >> prodFile2; fi
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$CI_USER_TOKEN"
  file_glob: true
  file:
    - "CITestTravis/file"
    - "prodFile2"
  skip_cleanup: true
  on:
    all_branches: true